function Footer() {
  return (
    <footer className="bg-light py-5 mt-auto">
      <div className="container">

        {/* Top Section */}
        <div className="row text-start">

          {/* Services */}
          <div className="col-md-3 mb-4">
            <h5 className="fw-bold">Services</h5>
            <ul className="list-unstyled">
              <li>Real Questions in our tests</li>
              <li>Skill Improvement</li>
              <li>Preparation for Exam</li>
            </ul>
          </div>

          
          <div className="col-md-3 mb-4">
            <h5 className="fw-bold">Assets</h5>
            <ul className="list-unstyled">
              <li>Images Generated By Gemini</li>
              <li>Question MCA Prepration book</li>
              <li>Most Questions From Digital Library</li>
            </ul>
          </div>

          {/* Support */}
          <div className="col-md-3 mb-4">
            <h5 className="fw-bold">Support</h5>
            <ul className="list-unstyled">
              <li>Contact</li>
               <li>shubhamshingne9@gmail.com</li>
            </ul>
          </div>

          {/* Address */}
          <div className="col-md-3 mb-4">
            <h5 className="fw-bold">Address</h5>
            <p className="mb-0 text-muted">
              Pune #1018,<br />
              Shikrapur,<br />
              412220
            </p>
          </div>

        </div>

        {/* Divider */}
        <hr />

        {/* Bottom Section */}
        <div className="d-flex justify-content-between align-items-center flex-wrap small text-muted">
          <p className="mb-0">© COPYRIGHT 2026. ALL RIGHTS RESERVED.</p>
          <p className="mb-0">Website Made by Shubham Avinash Shingne</p>
        </div>

      </div>
    </footer>
  );
}

export default Footer;